### ISSUE TITLE
Lab_1

### ISSUE THREAD

**Issue by Sageblatt** [FastBery/Labs_python_3sem#1]
Надо поправить:
1) В некоторых задачах уместно все графики отобразить на одной фигуре, однако в первом эпизоде было требование 2 о корректной передаче геометрии области (соотношение сторон).
2) dpi=40 или 100 маловато для современных мониторов. Например, в промышленной печати используют не менее 300 dpi, давайте ориентироваться на эту цифру.
3) Вместо str.replace() вот тут https://github.com/FastBery/Labs_python_3sem/blob/9e30a1c0ecab3f39256c3cacfc50decef838725b/lab_1/Episod_2/code.py#L13 и тут https://github.com/FastBery/Labs_python_3sem/blob/9e30a1c0ecab3f39256c3cacfc50decef838725b/lab_1/Episod_3/code.py#L10 следует использовать str.rstrip(), хотя в данных примерах str.split() работает корректно и убирает конец строки самостоятельно, так что str.replace() можно было вообще опустить. Если бы один из файлов был внезапно создан под Windows, то результат работы твоего кода мог бы измениться (если файл использует не LF, а CRLF в качестве конца строки). 
4) Во втором эпизоде подписи осей почти наезжают на названия последующих кадров, их надо бы разнести подальше.

Замечания, которые не являются ошибками, но которые стоит иметь в виду:
1) Тут https://github.com/FastBery/Labs_python_3sem/blob/9e30a1c0ecab3f39256c3cacfc50decef838725b/lab_1/Episod_1/code.py#L2 уместно было бы воспользоваться list comprehension вместо копипаста, ведь мы заранее знаем имена файлов и их количество.
2) На строчке https://github.com/FastBery/Labs_python_3sem/blob/9e30a1c0ecab3f39256c3cacfc50decef838725b/lab_1/Episod_1/code.py#L8 при запуске кода под Windows программа может упасть, так как разные ОС используют разные разделители директорий. Уместно было бы использовать os.path.join() или хотя бы os.path.sep.
3) 7-я пустая строка в первом эпизоде лишняя, так обычно куски кода друг от друга не отделяют. 
4) Тут https://github.com/FastBery/Labs_python_3sem/blob/9e30a1c0ecab3f39256c3cacfc50decef838725b/lab_1/Episod_2/code.py#L32 можно было воспользоваться f-строкой.
5) Во втором эпизоде шаг сетки выбрана немного странным образом, поэтому ей будет немного проблематично воспользоваться. (Желательно, чтобы она проходила по целым значениям по осям или по болеее-менее привычным дробным: 0.1, 0,25 и т.п.)
6) Для if необязательно брать в скобки проверяемое выражение.

**Comment by FastBery** [comment]
1. Я не понял как мне сделать КОРРЕКТНО соотношение сторон. На графике вроде всё отлично, но как сделать в коде я не знаю. Я довольно много гуглил и , если не знать что ты ищешь, информацию довольно сложно найти.
2. Про dpi... я использую 100 потому что если я буду использовать больше, то у меня всё увеличивается в несколько раз и начинает наезжать друг на друга. Возможно это как-то фиксится, но я хз как.
3. .....
4. Сделал (вроде)

**Comment by FastBery** [comment]
Как говориться "No hate", но требуется реально дохрена в сравнении с тем, что даётся на семинарах. Я был бы рад пофиксить всё это, но я тупой

**Comment by Sageblatt** [comment]
1. Но ты же нашёл ровно ту функцию, которая нужна: https://github.com/FastBery/Labs_python_3sem/blob/8147a44244bc5cf57f65b85c8c1501820fde6173/lab_1/Episod_1/code.py#L20 Тебе остался лишь маленький шажок -- в задании нет требования все графики уместить в одну картинку, ты можешь спокойно сделать каждому файлу свою png-шку. (И да, в случае, когда что-то совсем не получается -- всегда можно спросить, хуже от этого точно никому не будет)
2. Да, действительно, при просмотре через plt.show() картинка при большом dpi будет увеличиваться. В таком случае можно использовать параметр уже в функции plt.savefig, чтобы это учитывалось лишь при сохранении.
3. Это не было ошибкой, но поправить для чистоты кода и для обогащения знаний нужно было.
4. К сожалению, на обновлённой картинке всё стало ещё хуже. Однако тут опять же осталось совсем немного: подобрать нужные параметры вот тут https://github.com/FastBery/Labs_python_3sem/blob/8147a44244bc5cf57f65b85c8c1501820fde6173/lab_1/Episod_2/code.py#L43

**Comment by Sageblatt** [comment]
И да, я действительно забыл указать один очень важный момент -- хор6 за лабу у тебя в любом случае уже есть, поправишь основные пункты будет 8. Если пойдёт с замечаниями -- то ещё выше.
